name: Deploy Front-Arcadia manager to Production Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} << 'EOF'
          cd /root/arcadia-manager-frontend
          git pull origin main
          docker build -t arcadia-manager-front . 
          docker stop arcadia-manager-front
          docker rm arcadia-manager-front
          docker run -d --name arcadia-manager-front --restart unless-stopped -p 8080:80 -v /root/arcadia-manager-frontend/.env:/app/.env:ro arcadia-manager-front
          EOF
